# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 2.7.0"

group :test do
  gem "rspec", "~> 3.12"
end

group :development, :test do
  gem "rubocop", "~> 1.50", require: false
  gem "rubocop-rspec", "~> 2.20", require: false
end